
project_id = "cgrtrdwvkkhraizqukwt"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "https://quwik.com"
additional_redirect_urls = ["https://quwik.com/*", "http://localhost:5173/*", "http://localhost:3000/*"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
service_role_secret = ""

[analytics]
enabled = true
port = 54327

[storage]
enabled = true

[realtime]
enabled = true

[functions]
[functions.ola-maps-search]
verify_jwt = false
